# Generated by Django 5.0.3 on 2024-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Avances',
            },
        ),
        migrations.CreateModel(
            name='informes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'informes',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idObra', models.IntegerField(blank=True, null=True)),
                ('idDirector', models.IntegerField(blank=True, null=True)),
                ('idCapataz', models.IntegerField(blank=True, null=True)),
                ('idAyudante', models.IntegerField(blank=True, null=True)),
                ('idPeon', models.IntegerField(blank=True, null=True)),
                ('nombreObra', models.CharField(max_length=30)),
                ('estadoObra', models.CharField(max_length=10)),
                ('fechaInicioObra', models.DateField()),
            ],
            options={
                'db_table': 'obra',
            },
        ),
    ]
