# Generated by Django 5.0.3 on 2024-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avances',
            name='idUsuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avances',
            name='porcentajeAvance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informes',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='informes',
            name='georeferencias',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='informes',
            name='idInforme',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informes',
            name='idUsuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informes',
            name='notasDeVoz',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
