# Generated by Django 4.2.13 on 2024-10-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avances_idusuario_avances_porcentajeavance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignarTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDirector', models.IntegerField(blank=True, null=True)),
                ('idCapataz', models.IntegerField(blank=True, null=True)),
                ('idAyudante', models.IntegerField(blank=True, null=True)),
                ('idPeon', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'asignarTareas',
            },
        ),
    ]
